import path from "node:path";
import { readFile, writeFile } from "node:fs/promises";
import PizZip from "pizzip";
import Docxtemplater from "docxtemplater";
import {
  AlignmentType, BorderStyle, Document, ExternalHyperlink, Footer, HeadingLevel, HeightRule, ImageRun, LevelFormat,
  PageBreak, PageNumber, Packer, Paragraph, ShadingType, Table, TableCell, TableLayoutType, TableRow,
  TextRun, WidthType, type ISectionOptions
} from "docx";
import type { Block } from "../../spec/index.js";
import type { ArtifactRenderer, RenderContext } from "../types.js";

export interface DocxRenderOptions { engine: "auto" | "programmatic" | "template"; templatePath?: string; }
export interface DocxRenderer extends ArtifactRenderer { renderWithOptions(context: RenderContext, options: DocxRenderOptions): Promise<string>; }
type DocxtemplaterModule = object;
const premiumModules: DocxtemplaterModule[] = [];
export function registerDocxtemplaterModules(modules: DocxtemplaterModule[]): void { premiumModules.splice(0, premiumModules.length, ...modules); }
const text = (value: string, options: object = {}) => new TextRun({ text: value, ...options });
const heading = (value: string, level: 1 | 2 | 3) => new Paragraph({ text: value, heading: [HeadingLevel.HEADING_1, HeadingLevel.HEADING_2, HeadingLevel.HEADING_3][level - 1], keepNext: true });
const formHeading = (value: string, level: 1 | 2 | 3, accent: string, textColor: string) => new Paragraph({ keepNext: true, spacing: { before: level === 1 ? 360 : 200, after: 120 }, ...(level === 1 ? { border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: accent, space: 0 } } } : {}), children: [text(value, { bold: true, size: level === 1 ? 28 : 24, color: textColor })] });
function borders(color: string) { return { top: { style: BorderStyle.SINGLE, size: 2, color }, bottom: { style: BorderStyle.SINGLE, size: 2, color }, left: { style: BorderStyle.NIL }, right: { style: BorderStyle.NIL }, insideHorizontal: { style: BorderStyle.SINGLE, size: 1, color }, insideVertical: { style: BorderStyle.NIL } }; }
const noBorders = { top: { style: BorderStyle.NIL }, bottom: { style: BorderStyle.NIL }, left: { style: BorderStyle.NIL }, right: { style: BorderStyle.NIL }, insideHorizontal: { style: BorderStyle.NIL }, insideVertical: { style: BorderStyle.NIL } };
function fieldBorders(color: string) { return { top: { style: BorderStyle.NIL }, bottom: { style: BorderStyle.SINGLE, size: 2, color }, left: { style: BorderStyle.NIL }, right: { style: BorderStyle.NIL } }; }
function formHeaderBorders(accent: string, border: string) { return { top: { style: BorderStyle.NIL }, bottom: { style: BorderStyle.SINGLE, size: 6, color: accent }, left: { style: BorderStyle.NIL }, right: { style: BorderStyle.SINGLE, size: 1, color: border } }; }
function formDataBorders(color: string) { return { top: { style: BorderStyle.NIL }, bottom: { style: BorderStyle.SINGLE, size: 2, color }, left: { style: BorderStyle.NIL }, right: { style: BorderStyle.SINGLE, size: 1, color } }; }
function cellParagraphs(value: string | number | null, minLines = 1): Paragraph[] { const lines = String(value ?? "No disponible").split("\n"); while (lines.length < minLines) lines.push(""); return lines.map((line) => new Paragraph({ text: line || " ", spacing: { after: 0 } })); }
const writablePageWidth = 9638;
function tableColumnWidths(weights: number[] | undefined, count: number): number[] { const values = weights ?? Array.from({ length: count }, () => 1); const total = values.reduce((sum, value) => sum + value, 0); return values.map((value) => Math.round(value / total * writablePageWidth)); }
function cellWidth(weights: number[] | undefined, count: number, index: number) { return { size: tableColumnWidths(weights, count)[index], type: WidthType.DXA }; }
async function blockToDocx(block: Block, ctx: RenderContext, key: string): Promise<Array<Paragraph | Table>> {
  switch (block.type) {
    case "paragraph": return [new Paragraph({ children: [text(block.text)], spacing: { after: 150 }, widowControl: true })];
    case "heading": return [ctx.spec.documentMode === "form" ? formHeading(block.text, block.level, ctx.theme.colors.accent, ctx.theme.colors.text) : heading(block.text, block.level)];
    case "fieldGrid": { const widths = tableColumnWidths(undefined, block.columns); const rows: TableRow[] = []; for (let index = 0; index < block.fields.length; index += block.columns) { const fields = block.fields.slice(index, index + block.columns); while (fields.length < block.columns) fields.push(""); rows.push(new TableRow({ cantSplit: true, children: fields.map((field, column) => new TableCell({ width: { size: widths[column], type: WidthType.DXA }, borders: fieldBorders(ctx.theme.colors.border), children: [new Paragraph({ spacing: { after: 40 }, children: [text(field, { bold: true, size: 18, color: ctx.theme.colors.muted })] }), ...cellParagraphs("", block.lines)] })) })); } return [new Table({ width: { size: writablePageWidth, type: WidthType.DXA }, columnWidths: widths, layout: TableLayoutType.FIXED, borders: noBorders, rows }), new Paragraph({ spacing: { after: 120 } })]; }
    case "ruledLines": return [new Table({ width: { size: writablePageWidth, type: WidthType.DXA }, columnWidths: [writablePageWidth], layout: TableLayoutType.FIXED, borders: noBorders, rows: Array.from({ length: block.count }, () => new TableRow({ cantSplit: true, height: { value: 260, rule: HeightRule.EXACT }, children: [new TableCell({ width: { size: writablePageWidth, type: WidthType.DXA }, borders: fieldBorders(ctx.theme.colors.border), children: [new Paragraph({ text: "\u00A0" })] })] })) }), new Paragraph({ spacing: { after: 200 } })];
    case "bullets": return block.items.map((item) => new Paragraph({ text: item, numbering: { reference: "artifact-bullets", level: 0 }, style: "Body" }));
    case "numberedList": return block.items.map((item) => new Paragraph({ text: item, numbering: { reference: "artifact-numbered", level: 0 }, style: "Body" }));
    case "quote": return [new Paragraph({ children: [text(block.text, { italics: true }), ...(block.attribution ? [text(` — ${block.attribution}`, { bold: true })] : [])], style: "Quote" })];
    case "callout": return [new Paragraph({ children: [text(`${block.title}. `, { bold: true }), text(block.text)], style: "Callout", shading: { type: ShadingType.CLEAR, fill: ctx.theme.callouts[block.tone] }, border: { left: { style: BorderStyle.SINGLE, size: 16, color: ctx.theme.colors.accent, space: 4 } } })];
    case "kpiGrid": return [new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, borders: borders(ctx.theme.colors.border), rows: [new TableRow({ children: block.items.map((k) => new TableCell({ shading: { fill: ctx.theme.colors.surface }, children: [new Paragraph({ children: [text(k.label, { color: ctx.theme.colors.muted, size: 18 })] }), new Paragraph({ children: [text(k.value, { bold: true, size: 32 })] }), ...(k.context ? [new Paragraph({ children: [text(k.context, { color: ctx.theme.colors.muted, size: 16 })] })] : [])] })) })] })];
    case "table": { const formStyle = block.table.style === "form"; return [new Table({ width: { size: writablePageWidth, type: WidthType.DXA }, columnWidths: tableColumnWidths(block.table.columnWeights, block.table.columns.length), layout: TableLayoutType.FIXED, borders: formStyle ? noBorders : borders(ctx.theme.colors.border), rows: [new TableRow({ tableHeader: true, cantSplit: true, children: block.table.columns.map((c, i) => new TableCell({ width: cellWidth(block.table.columnWeights, block.table.columns.length, i), ...(formStyle ? { borders: formHeaderBorders(ctx.theme.colors.accent, ctx.theme.colors.border) } : { shading: { fill: ctx.theme.tables.headerFill } }), children: [new Paragraph({ children: [text(c, { bold: true })] })] })) }), ...block.table.rows.map((row) => new TableRow({ cantSplit: true, children: row.map((v, i) => new TableCell({ width: cellWidth(block.table.columnWeights, block.table.columns.length, i), ...(formStyle ? { borders: formDataBorders(ctx.theme.colors.border) } : {}), children: cellParagraphs(v, block.table.rowLines ?? 1) })) }))] }), new Paragraph({ spacing: { after: 120 } })]; }
    case "chart": case "diagram": case "image": { const imagePath = ctx.assets.get(`${key}-png`) ?? ctx.assets.get(key); if (!imagePath) return [new Paragraph({ text: "Visualización no disponible", style: "Callout" })]; const data = await readFile(imagePath); const alt = block.type === "chart" ? block.chart.title : block.type === "diagram" ? block.diagram.title : block.caption ?? "Imagen"; return [new Paragraph({ alignment: AlignmentType.CENTER, keepNext: true, children: [new ImageRun({ type: "png", data, transformation: { width: 620, height: block.type === "diagram" ? 320 : 280 }, altText: { title: alt, description: alt, name: alt } })] }), new Paragraph({ alignment: AlignmentType.CENTER, style: "Caption", text: block.type === "chart" ? block.chart.insight ?? block.chart.title : block.type === "diagram" ? block.diagram.caption ?? block.diagram.title : block.caption ?? "" })]; }
    case "code": return [new Paragraph({ style: "Code", children: block.code.split("\n").flatMap((line, i) => [text(line), ...(i < block.code.split("\n").length - 1 ? [new TextRun({ break: 1 })] : [])]) })];
    case "comparison": return [new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, borders: borders(ctx.theme.colors.border), rows: [new TableRow({ children: [block.left, block.right].map((side) => new TableCell({ children: [new Paragraph({ children: [text(side.title, { bold: true, color: ctx.theme.colors.accent })] }), ...side.items.map((i) => new Paragraph({ text: i, bullet: { level: 0 } }))] })) })] })];
    case "timeline": return [new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, borders: borders(ctx.theme.colors.border), rows: [new TableRow({ children: block.items.map((i) => new TableCell({ shading: { fill: ctx.theme.colors.surface }, children: [new Paragraph({ children: [text(i.date, { bold: true, color: ctx.theme.colors.accent })] }), new Paragraph({ children: [text(i.title, { bold: true })] }), ...(i.detail ? [new Paragraph({ children: [text(i.detail, { color: ctx.theme.colors.muted, size: 18 })] })] : [])] })) })] })];
    case "riskMatrix": return [new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, borders: borders(ctx.theme.colors.border), rows: [new TableRow({ tableHeader: true, children: ["Riesgo", "Prob.", "Impacto", "Mitigación"].map((c) => new TableCell({ shading: { fill: ctx.theme.tables.headerFill }, children: [new Paragraph({ children: [text(c, { bold: true })] })] })) }), ...block.items.map((r) => new TableRow({ children: [r.risk, r.probability, r.impact, r.mitigation].map((v) => new TableCell({ children: [new Paragraph(v)] })) }))] })];
    case "pageBreak": case "slideBreak": return [new Paragraph({ children: [new PageBreak()] })];
    case "columns": { const cells: TableCell[] = []; for (const col of block.columns) { const children: Array<Paragraph | Table> = []; for (const nested of col) children.push(...await blockToDocx(nested, ctx, key)); cells.push(new TableCell({ children })); } return [new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, borders: { top: { style: BorderStyle.NIL }, bottom: { style: BorderStyle.NIL }, left: { style: BorderStyle.NIL }, right: { style: BorderStyle.NIL }, insideHorizontal: { style: BorderStyle.NIL }, insideVertical: { style: BorderStyle.NIL } }, rows: [new TableRow({ children: cells })] })]; }
  }
  throw new Error("Unsupported block");
}
export class ProgrammaticDocxRenderer implements DocxRenderer {
  readonly format = "docx" as const; render(ctx: RenderContext) { return this.renderWithOptions(ctx, { engine: "programmatic" }); }
  async renderWithOptions(ctx: RenderContext, _options: DocxRenderOptions): Promise<string> {
    const formMode = ctx.spec.documentMode === "form";
    const logoPath = ctx.spec.brand?.logoAssetId ? ctx.assets.get(`asset:${ctx.spec.brand.logoAssetId}`) : undefined; const logoData = logoPath ? await readFile(logoPath) : undefined;
    const formHeader: Array<Paragraph | Table> = logoData ? [new Table({ width: { size: writablePageWidth, type: WidthType.DXA }, columnWidths: [7600, 2038], layout: TableLayoutType.FIXED, borders: noBorders, rows: [new TableRow({ cantSplit: true, children: [new TableCell({ width: { size: 7600, type: WidthType.DXA }, borders: noBorders, children: [new Paragraph({ spacing: { after: 70 }, children: [text(ctx.spec.meta.title, { bold: true, size: 36 })] }), new Paragraph({ spacing: { after: 100 }, children: [text(ctx.spec.meta.subtitle ?? "", { color: ctx.theme.colors.muted, size: 20 })] })] }), new TableCell({ width: { size: 2038, type: WidthType.DXA }, borders: noBorders, verticalAlign: "center", children: [new Paragraph({ alignment: AlignmentType.RIGHT, children: [new ImageRun({ type: "png", data: logoData, transformation: { width: 106, height: 64 }, altText: { title: "Logo", description: "Logo de la organización", name: "Logo" } })] })] })] })] })] : [new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 100 }, children: [text(ctx.spec.meta.title, { bold: true, size: 36 })] }), new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 140 }, children: [text(ctx.spec.meta.subtitle ?? "", { color: ctx.theme.colors.muted, size: 20 })] })];
    const children: Array<Paragraph | Table> = formMode ? formHeader : [new Paragraph({ text: ctx.spec.meta.title, style: "Title" }), new Paragraph({ text: ctx.spec.meta.subtitle ?? "", style: "Subtitle" }), new Paragraph({ text: [ctx.spec.meta.author, ctx.spec.meta.organization, ctx.spec.meta.date].filter(Boolean).join(" · "), alignment: AlignmentType.CENTER }), ...(ctx.spec.meta.sampleData ? [new Paragraph({ text: "SAMPLE DATA — datos ficticios para demostración", style: "Callout", alignment: AlignmentType.CENTER })] : []), new Paragraph({ children: [new PageBreak()] }), heading("Contenido", 1), ...ctx.spec.sections.map((section) => new Paragraph({ text: section.title, numbering: { reference: "artifact-toc", level: 0 }, style: "Body" })), new Paragraph({ children: [new PageBreak()] })];
    for (const [si, section] of ctx.spec.sections.entries()) { if (!formMode && si > 0) children.push(new Paragraph({ children: [new PageBreak()] })); children.push(formMode ? formHeading(section.title, 1, ctx.theme.colors.accent, ctx.theme.colors.text) : heading(section.title, 1)); if (section.subtitle) children.push(new Paragraph({ text: section.subtitle, style: formMode ? "Body" : "Subtitle", spacing: formMode ? { after: 140 } : undefined })); for (const [bi, block] of section.blocks.entries()) children.push(...await blockToDocx(block, ctx, `${si}-${bi}`)); }
    if (!formMode && ctx.spec.sources.length) { children.push(heading("Fuentes", 1)); for (const source of ctx.spec.sources) { const runs = [text(`${source.sample ? "[SAMPLE] " : ""}${source.title}`, { bold: true })]; if (source.publisher) runs.push(text(` — ${source.publisher}`)); if (source.url) runs.push(text(" · "), new ExternalHyperlink({ link: source.url, children: [text(source.url, { style: "Hyperlink" })] }) as any); children.push(new Paragraph({ children: runs as any[] })); } }
    const section: ISectionOptions = { properties: { titlePage: true, page: { margin: { top: 1134, right: 1134, bottom: 1134, left: 1134 } } }, footers: { default: new Footer({ children: [new Paragraph({ alignment: AlignmentType.RIGHT, children: formMode ? [new TextRun({ children: [PageNumber.CURRENT], size: 16, color: ctx.theme.colors.muted })] : [text(ctx.spec.meta.title, { color: ctx.theme.colors.muted, size: 16 }), text("  ·  "), new TextRun({ children: [PageNumber.CURRENT], size: 16 })] })] }) }, children };
    const doc = new Document({ features: { updateFields: true }, creator: ctx.spec.meta.author ?? "Artifact Studio", title: ctx.spec.meta.title, description: ctx.spec.meta.purpose, styles: { default: { document: { run: { font: "IBM Plex Sans", size: 21, color: ctx.theme.colors.text }, paragraph: { spacing: { after: 120, line: 290 } } } }, paragraphStyles: [{ id: "Title", name: "Title", basedOn: "Normal", next: "Subtitle", run: { size: 54, bold: true, color: ctx.theme.colors.text, font: "IBM Plex Sans" }, paragraph: { alignment: AlignmentType.CENTER, spacing: { before: 2200, after: 240 }, keepNext: true } }, { id: "Subtitle", name: "Subtitle", basedOn: "Normal", next: "Body", run: { size: 28, color: ctx.theme.colors.muted, font: "IBM Plex Sans" }, paragraph: { alignment: AlignmentType.CENTER, spacing: { after: 360 } } }, { id: "Body", name: "Body", basedOn: "Normal", next: "Body", run: { size: 21 } }, { id: "Caption", name: "Caption", basedOn: "Normal", next: "Body", run: { size: 18, italics: true, color: ctx.theme.colors.muted }, paragraph: { keepNext: true, spacing: { after: 180 } } }, { id: "Quote", name: "Quote", basedOn: "Normal", next: "Body", run: { size: 23, italics: true }, paragraph: { indent: { left: 540, right: 540 }, spacing: { before: 180, after: 180 } } }, { id: "Callout", name: "Callout", basedOn: "Normal", next: "Body", run: { size: 20 }, paragraph: { indent: { left: 240, right: 240 }, spacing: { before: 150, after: 180 } } }, { id: "Code", name: "Code", basedOn: "Normal", next: "Body", run: { font: "IBM Plex Mono", size: 18 }, paragraph: { shading: { fill: "F1F5F9" }, indent: { left: 220, right: 220 }, spacing: { before: 120, after: 160 } } }] }, numbering: { config: [{ reference: "artifact-bullets", levels: [{ level: 0, format: LevelFormat.BULLET, text: "•", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 540, hanging: 260 } } } }] }, { reference: "artifact-numbered", levels: [{ level: 0, format: LevelFormat.DECIMAL, text: "%1.", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 540, hanging: 260 } } } }] }, { reference: "artifact-toc", levels: [{ level: 0, format: LevelFormat.DECIMAL, text: "%1.", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 420, hanging: 220 } } } }] }] }, sections: [section] });
    const output = path.join(ctx.outputDir, `${ctx.basename}.docx`); await writeFile(output, await Packer.toBuffer(doc)); return output;
  }
}
export class TemplateDocxRenderer implements DocxRenderer { readonly format = "docx" as const; render(ctx: RenderContext) { return this.renderWithOptions(ctx, { engine: "template" }); } async renderWithOptions(ctx: RenderContext, options: DocxRenderOptions): Promise<string> { if (!options.templatePath) throw new Error("Docxtemplater requires an explicit audited templatePath; PRO modules are optional and not bundled"); const template = await readFile(options.templatePath); const engine = new Docxtemplater(new PizZip(template), { paragraphLoop: true, linebreaks: true, modules: premiumModules as any[] }); engine.render({ meta: ctx.spec.meta, theme: ctx.spec.theme, sections: ctx.spec.sections, sources: ctx.spec.sources, assets: ctx.spec.assets }); const output = path.join(ctx.outputDir, `${ctx.basename}.docx`); await writeFile(output, engine.getZip().generate({ type: "nodebuffer" })); return output; } }
export class AutoDocxRenderer implements DocxRenderer { readonly format = "docx" as const; constructor(private readonly programmatic = new ProgrammaticDocxRenderer(), private readonly template = new TemplateDocxRenderer()) {} render(ctx: RenderContext) { return this.renderWithOptions(ctx, { engine: (process.env.DOCX_ENGINE as DocxRenderOptions["engine"]) ?? "auto" }); } async renderWithOptions(ctx: RenderContext, options: DocxRenderOptions): Promise<string> { if (options.engine === "template" || (options.engine === "auto" && options.templatePath && process.env.DOCXTEMPLATER_PRO === "true")) { try { return await this.template.renderWithOptions(ctx, options); } catch (error) { if (options.engine === "template") throw error; } } return this.programmatic.renderWithOptions(ctx, options); } }
