import path from "node:path";
import PptxGenJSImport from "pptxgenjs";
import type { Block } from "../../spec/index.js";
import type { Theme } from "../../theme/index.js";
import { VegaChartRenderer } from "../../charts/index.js";
import type { ArtifactRenderer, RenderContext } from "../types.js";

const LAYOUTS = ["TITLE", "SECTION", "AGENDA", "EXECUTIVE_SUMMARY", "KPI_GRID", "CONTENT", "TWO_COLUMNS", "TEXT_VISUAL", "FULL_VISUAL", "CHART", "CHART_WITH_INSIGHT", "TABLE", "ARCHITECTURE", "PROCESS", "TIMELINE", "RISKS", "COMPARISON", "QUOTE", "CONCLUSION", "APPENDIX"] as const;
const PptxGenJS = PptxGenJSImport as unknown as { new(): any };
function selectLayout(blocks: Block[], title: string): typeof LAYOUTS[number] { if (/conclus|recom/i.test(title)) return "CONCLUSION"; if (blocks.some((b) => b.type === "kpiGrid")) return "KPI_GRID"; if (blocks.some((b) => b.type === "riskMatrix")) return "RISKS"; if (blocks.some((b) => b.type === "timeline")) return "TIMELINE"; if (blocks.some((b) => b.type === "comparison")) return "COMPARISON"; if (blocks.some((b) => b.type === "diagram")) return "ARCHITECTURE"; if (blocks.some((b) => b.type === "chart")) return "CHART_WITH_INSIGHT"; if (blocks.some((b) => b.type === "table")) return "TABLE"; return "CONTENT"; }
function masters(pptx: any, theme: Theme): void { for (const title of LAYOUTS) pptx.defineSlideMaster({ title, background: { color: theme.colors.background }, objects: [{ rect: { x: 0.65, y: 0.62, w: 0.08, h: 0.42, fill: { color: theme.colors.accent }, line: { color: theme.colors.accent } } }, { placeholder: { options: { name: "title", type: "title", x: 0.88, y: 0.45, w: 11.7, h: 0.65, fontFace: theme.typography.sans, fontSize: theme.typography.titlePt, bold: true, color: theme.colors.text }, text: "" } }, { text: { text: "ARTIFACT STUDIO", options: { x: 0.65, y: 7.08, w: 2.2, h: 0.18, fontFace: theme.typography.sans, fontSize: 7, color: theme.colors.muted, charSpacing: 1.5 } } }], slideNumber: { x: 12.2, y: 7.03, w: 0.45, h: 0.2, fontSize: 8, color: theme.colors.muted }, margin: 0 }); }
function addTitle(slide: any, title: string, theme: Theme): void { slide.addText(title, { placeholder: "title", fontFace: theme.typography.sans, fontSize: title.length > 55 ? 27 : 32, bold: true, color: theme.colors.text, breakLine: false, fit: "shrink" } as any); }
function addBody(pptx: any, slide: any, blocks: Block[], theme: Theme, assets: Map<string, string>, si: number): void {
  let y = 1.35; const bodyW = 12.0;
  for (const [bi, b] of blocks.entries()) {
    if (b.type === "paragraph") { slide.addText(b.text, { x: .75, y, w: bodyW, h: .65, fontFace: theme.typography.sans, fontSize: 18, color: theme.colors.text, margin: 0.03, valign: "top", fit: "shrink" }); y += .82; }
    else if (b.type === "bullets" || b.type === "numberedList") { slide.addText(b.items.map((text, i) => ({ text, options: { bullet: b.type === "bullets" ? { indent: 18 } : { type: "number", indent: 18 }, breakLine: i < b.items.length - 1 } })), { x: .85, y, w: 11.7, h: Math.min(3.8, .45 * b.items.length + .25), fontFace: theme.typography.sans, fontSize: 18, color: theme.colors.text, breakLine: true, paraSpaceAfterPt: 8, margin: .02, fit: "shrink" } as any); y += Math.min(3.9, .48 * b.items.length + .35); }
    else if (b.type === "kpiGrid") { const cols = Math.min(4, b.items.length), w = (12 - (cols - 1) * .2) / cols; b.items.forEach((k, i) => { const x = .67 + (i % cols) * (w + .2), yy = y + Math.floor(i / cols) * 1.45; slide.addShape(pptx.ShapeType.roundRect, { x, y: yy, w, h: 1.2, rectRadius: .04, fill: { color: theme.colors.surface }, line: { color: theme.colors.border, width: .8 } }); slide.addText(k.label, { x: x + .16, y: yy + .14, w: w - .3, h: .22, fontSize: 10, color: theme.colors.muted, charSpacing: .5, margin: 0 }); slide.addText(k.value, { x: x + .16, y: yy + .43, w: w - .3, h: .42, fontSize: 24, bold: true, color: theme.colors.text, margin: 0 }); if (k.context) slide.addText(k.context, { x: x + .16, y: yy + .9, w: w - .3, h: .18, fontSize: 9, color: theme.colors.muted, margin: 0 }); }); y += Math.ceil(b.items.length / cols) * 1.45; }
    else if (b.type === "chart") { const native = new VegaChartRenderer().renderPptxNative(b.chart); if (native) slide.addChart((pptx.ChartType as any)[native.type] ?? (pptx.ChartType as any).bar, native.data, { x: .75, y, w: 8.2, h: 4.7, showLegend: native.data.length > 1, legendPos: "b", showTitle: false, chartColors: [...theme.chartPalette], catAxisLabelFontFace: theme.typography.sans, valAxisLabelFontFace: theme.typography.sans, showValue: native.type === "bar", showCatName: false, showPercent: native.type === "pie" || native.type === "doughnut", valAxisMinVal: native.type === "bar" ? 0 : undefined, showBorder: false } as any); else { const asset = assets.get(`${si}-${bi}`); if (asset) slide.addImage({ path: asset, x: .75, y, w: 8.2, h: 4.7, altText: b.chart.title }); } if (b.chart.insight) { slide.addShape(pptx.ShapeType.rect, { x: 9.3, y: y + .3, w: 3.25, h: 2.2, fill: { color: theme.colors.accentSoft }, line: { color: theme.colors.accentSoft } }); slide.addText("INSIGHT", { x: 9.55, y: y + .55, w: 2.7, h: .2, fontSize: 9, bold: true, color: theme.colors.accent, charSpacing: 1.2, margin: 0 }); slide.addText(b.chart.insight, { x: 9.55, y: y + .9, w: 2.65, h: 1.2, fontSize: 17, bold: true, color: theme.colors.text, margin: 0, fit: "shrink" }); } y += 4.9; }
    else if (b.type === "diagram") { const asset = assets.get(`${si}-${bi}`); if (asset) slide.addImage({ path: asset, x: .85, y, w: 11.6, h: 4.9, altText: b.diagram.title }); y += 5; }
    else if (b.type === "table") { slide.addTable([b.table.columns, ...b.table.rows.map((r) => r.map((v) => v === null ? "No disponible" : String(v)))], { x: .75, y, w: 11.8, h: 4.7, border: { type: "solid", color: theme.colors.border, pt: .5 }, fill: theme.colors.surface, color: theme.colors.text, fontFace: theme.typography.sans, fontSize: 13, margin: .08, bold: false, autoFit: false, rowH: .45 } as any); y += 4.8; }
    else if (b.type === "riskMatrix") { slide.addTable([["Riesgo", "Prob.", "Impacto", "Mitigación"], ...b.items.map((r) => [r.risk, r.probability, r.impact, r.mitigation])], { x: .75, y, w: 11.8, h: 4.8, border: { color: theme.colors.border, pt: .5 }, fill: theme.colors.surface, color: theme.colors.text, fontFace: theme.typography.sans, fontSize: 13, margin: .08, rowH: .5 } as any); y += 4.9; }
    else if (b.type === "timeline") { b.items.forEach((item, i) => { const x = .8 + i * (11.5 / Math.max(1, b.items.length - 1)); slide.addShape(pptx.ShapeType.ellipse, { x: x - .09, y: y + .45, w: .18, h: .18, fill: { color: item.status === "done" ? theme.colors.positive : theme.colors.accent }, line: { color: theme.colors.background } }); if (i < b.items.length - 1) slide.addShape(pptx.ShapeType.line, { x: x + .1, y: y + .54, w: 11.5 / Math.max(1, b.items.length - 1) - .2, h: 0, line: { color: theme.colors.border, width: 1.4 } }); slide.addText(item.date, { x: x - .65, y, w: 1.3, h: .22, align: "center", fontSize: 10, bold: true, color: theme.colors.accent, margin: 0 }); slide.addText(item.title, { x: x - .75, y: y + .82, w: 1.5, h: .55, align: "center", fontSize: 12, color: theme.colors.text, margin: 0, fit: "shrink" }); }); y += 2; }
    else if (b.type === "callout") { slide.addShape(pptx.ShapeType.rect, { x: .75, y, w: 11.8, h: .9, fill: { color: theme.callouts[b.tone] }, line: { color: theme.callouts[b.tone] } }); slide.addText([{ text: `${b.title}  `, options: { bold: true } }, { text: b.text }], { x: 1, y: y + .2, w: 11.2, h: .45, fontSize: 16, color: theme.colors.text, margin: 0, fit: "shrink" }); y += 1.1; }
    else if (b.type === "comparison") { [b.left, b.right].forEach((side, i) => { const x = .75 + i * 6; slide.addText(side.title, { x, y, w: 5.6, h: .4, fontSize: 18, bold: true, color: theme.colors.accent, margin: 0 }); slide.addText(side.items.map((text) => ({ text, options: { bullet: { indent: 16 }, breakLine: true } })), { x, y: y + .5, w: 5.5, h: 1.7, fontSize: 15, color: theme.colors.text, margin: .03, fit: "shrink" } as any); }); y += 2.35; }
  }
}
export class PptxRenderer implements ArtifactRenderer { readonly format = "pptx" as const; async render(ctx: RenderContext): Promise<string> { const pptx = new PptxGenJS(); pptx.layout = "LAYOUT_WIDE"; pptx.author = ctx.spec.meta.author ?? "Artifact Studio"; pptx.subject = ctx.spec.meta.purpose ?? ""; pptx.title = ctx.spec.meta.title; pptx.company = ctx.spec.meta.organization ?? ""; pptx.lang = "es-AR"; pptx.theme = { headFontFace: ctx.theme.typography.sans, bodyFontFace: ctx.theme.typography.sans, lang: "es-AR" }; masters(pptx, ctx.theme); const cover = pptx.addSlide({ masterName: "TITLE" }); cover.background = { color: ctx.theme.colors.background }; cover.addText("ARTIFACT STUDIO", { x: .8, y: 1.15, w: 3, h: .25, fontSize: 10, bold: true, color: ctx.theme.colors.accent, charSpacing: 2, margin: 0 }); cover.addText(ctx.spec.meta.title, { x: .8, y: 1.7, w: 10.9, h: 1.5, fontSize: 38, bold: true, color: ctx.theme.colors.text, margin: 0, fit: "shrink" }); if (ctx.spec.meta.subtitle) cover.addText(ctx.spec.meta.subtitle, { x: .8, y: 3.45, w: 9.8, h: .65, fontSize: 21, color: ctx.theme.colors.muted, margin: 0 }); cover.addShape(pptx.ShapeType.line, { x: .8, y: 5.7, w: 2.2, h: 0, line: { color: ctx.theme.colors.accent, width: 3 } }); cover.addText([ctx.spec.meta.author, ctx.spec.meta.organization, ctx.spec.meta.date].filter(Boolean).join(" · "), { x: .8, y: 5.95, w: 10, h: .3, fontSize: 12, color: ctx.theme.colors.muted, margin: 0 }); if (ctx.spec.meta.sampleData) cover.addText("SAMPLE DATA · DATOS FICTICIOS", { x: 9.3, y: 6.65, w: 3.2, h: .28, fontSize: 10, bold: true, color: ctx.theme.colors.warning, align: "right", margin: 0 }); ctx.spec.sections.forEach((section, si) => { const layout = selectLayout(section.blocks, section.title); const slide = pptx.addSlide({ masterName: layout }); addTitle(slide, section.title, ctx.theme); if (section.subtitle) slide.addText(section.subtitle, { x: .9, y: 1.08, w: 11.4, h: .25, fontSize: 11, color: ctx.theme.colors.muted, margin: 0 }); addBody(pptx, slide, section.blocks, ctx.theme, ctx.assets, si); }); const output = path.join(ctx.outputDir, `${ctx.basename}.pptx`); await pptx.writeFile({ fileName: output }); return output; } }
